---
sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "10.16.3"
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - nhquocvinh@gmail.com
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm i -g react-deploy-cli
  - npm run build
before_script:
  - export RELEASE_HEAD=$(git rev-parse --short HEAD | cut -c1-7)
  - export RELEASE_HEAD_LONG=$(git rev-parse HEAD)
  - export CI=false
deploy:
  provider: s3
  access_key_id: AKIA2JHQ45NBHMZORRV5
  secret_access_key:
    secure: BJcA0ir2vQekshJ86qQN6ZEt09AlY0tgJo2XjPmqOB8qCEwoNg5YhXBrBSWVvmTbmi9c6pbjmMsfbzPzzKckaumer9asfBPwPQ2gowivRLBKqWmpQ9nLRYaCsTzjQjMhX8qWzRt7gQeQ18rbP5YvmkaHiS6ODE09eFTCVOXYDeo5zgqU7TLgYMc1a5odGmOnKkCGxyKt53XLDe9g+vOla6s8X6MDoLJ1k427wxH+7fJpCiCgnEUSn+jaAPNr4VLqVLjT2COqcMxJkwE+KnfW5GWY9m0nifQPNXvzwhyK7zz1RYM6siQ6jU+Lvmh63x8Z1erQGSwQs8vI5uzrh9xse1TCM2UrJtoeQ09UXt21eJIr5YAv9SJ8lM5CUrRx5GmyDW6avbuK3guav3NfAv0eCb18qki+psdZeYrtb6U3bg9Av25Ox4Ps0UpaN3TE+dlmSHKDygrVBDlHRnYXsSVm2j5bddFwlaS/r2OF4YXHQEHcC2KyEpGeHCBmd58tkNNWXfcdJcQzqy2MalBTu0xbPdKFwvE8WqZmWPym8XuYeIDtarcQ4Wih7rfAMBg7pOF3tRKTJSvdJGF0yJdnyS8qrNsIucerfBp9vszbp4JGxGN22xxJbIOwZhDa08UgIMtEwbYjRauVdGDIMVThhjHXVvJb7qwFYvD7uMuU0bOgc9Y=
  bucket: vinhnhq-prod
  acl: public_read
  skip_cleanup: true
  local_dir: build
  branches:
  only:
    - master
